### ISSUE TITLE
evaluation pipeline improvements

### ISSUE THREAD

**Issue by dlaehnemann** [hzi-bifo/mdasim#9]
The following points result from discussion of Issue #2, but would confuse the discussion in that thread -- so here's a new issue for them.

A couple of small things I would like to modify in the pipeline to slightly improve it:

1. The `SAM` output of `minimap2` can be piped directly into `samtools view`, so that we can directly write the `BAM` file to disc from the `minimap2` rule and skip writing the `SAM` file we won't need later on.
2. That `BAM` file can be marked as a temporary file, so that it gets deleted automatically by Snakemake once the downstream files have been created from it (i.e. the sorted bam file): `"{outfolder}/aln.bam"` would become `temp("{outfolder}/aln.bam")`
3. For a clearer interpretation of the logging output, we want to rename `log_cnt` to `mdasim_cnt` and `sum_cnt` to `aln_cnt`.

And one slightly larger change will be to:
1. Remove the config.yaml, I don't think we currently need it.
2. Instead include some example input files for the testing in the parent folder of the testing pipeline (`examples`) or the `examples/testing` folder itself (see what works best for the following point).
3. Propagate their naming through the pipeline with wildcards, so that only the rule all will contain the run-specific naming information and will call in the appropriate input files at the start of the pipeline.

**Comment by VSack** [comment]
## removal of the config.yaml
I didn't use wildcards for this one, since the filenames are each needed in one rule only. Instead, I declared variables for the three files in the beginning of the Snakefile, to provide a single point of truth for future changes, which can be found fast and easy.

## including examples
I added an `input`-folder, however, I had to zip the `outAmplicons.fasta`-file, since Github doesn't accept files larger than 100MB. It's not the most elegant solution since a user has to unzip the file before usage, but it was the only thing that came to my mind right away.
[Github Conditions for large files](https://help.github.com/articles/conditions-for-large-files/)
